const products = [
    {
        _id: '1',
        name: 'Samsung Galaxy S10', 
        image: '/images/SamsungGalaxyS10.png',
        description: 'Samsung Galaxy S10 stands with a bezel-less screen and corning Gorilla glass shield. 6.1-inch screen possessing Quad HD+ dynamic AMOLED display. 120 HZ refresh rate to let the scenes flow with smoothness. Snapdragon 855 chipset carries the commands with high responsiveness. Triple cameras (Wide, Ultra-wide, and Telephoto) capture a scene with multiple styles. Super- slow motion to record video at 960fps with HD support and FHD at 240fps. Support 4K UHD video recording up to 60fps. A battery can stand by for 18 hours at video playback activity.',
        brand: 'Samsung',
        price: 273,
        countInStock: 15,
        rating: 3.6,
        numReviews: 5,
    },
    {
        _id: '2',
        name: 'iPhone 13 Pro Max', 
        image: '/images/iPhone13ProMax.png',
        description: "The iPhone 13 Pro Max is Apple's biggest phone in the lineup with a massive, 6.7\" screen that for the first time in an iPhone comes with 120Hz ProMotion display that ensures super smooth scrolling. The benefit of such a gigantic phone is that it also comes with the biggest battery of all iPhone 13 series.",
        brand: 'Apple',
        price: 1799,
        countInStock: 11,
        rating: 4.5,
        numReviews: 12,
    },
    {
        _id: '3',
        name: 'Pixel 6a', 
        image: '/images/Pixel6a.png',
        description: 'Smart, powerful, helpful. And less than you think. It\'s the more affordable, super fast and secure Google phone. Powered by Google Tensor for fast performance. Adaptive Battery can last over 24 hours.',
        brand: 'Google',
        price: 749,
        countInStock: 2,
        rating: 2.8,
        numReviews: 11,
    },
    {
        _id: '4',
        name: 'Samsung Galaxy Z Flip4', 
        image: '/images/SamsungGalaxyZFlip4.png',
        description: 'Introducing the Samsung Galaxy Z Flip4: fold it, flip it, stand it. Capture photos and videos hands-free with a camera designed to stand on its own with revolutionary folding glass or get that quick selfie when folded for moments that can’t wait. Stay in the loop with the cover screen, which lets you take calls, send messages, access apps and so much more – all without opening your phone. Experience the full screen durable smartphone that folds in your pocket or small bag and designed to be unlike anything you’ve held before.',
        brand: 'Samsung',
        price: 1499,
        countInStock: 23,
        rating: 3.8,
        numReviews: 22,
    },
    {
        _id: '5',
        name: 'iPhone 14 Pro Max 128GB', 
        image: '/images/iPhone14ProMax128GB.png',
        description: 'The iPhone 14 Pro Max isn’t just the most powerful phone around. It’s a joy to use, thanks to the clever new Dynamic Island for displaying notifications and live activities. Apple’s largest Pro model also delivers fantastic cameras — including a new 48MP main shooter — an always-on display, compelling Action mode for video and excellent battery life. It’s pricey, but it’s also the best phone money can buy.',
        brand: 'Apple',
        price: 1899,
        countInStock: 23,
        rating: 4.6,
        numReviews: 22,
    }
]

export default products